# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SharkKMeansTrain <- function(X, k) {
    .Call('LearningRcppShark_SharkKMeansTrain', PACKAGE = 'LearningRcppShark', X, k)
}

SharkKMeansPredict <- function(X, centroids) {
    .Call('LearningRcppShark_SharkKMeansPredict', PACKAGE = 'LearningRcppShark', X, centroids)
}

